-- FNG local demo seed. Generated for local Docker/Supabase development.
-- Loaded automatically by `supabase db reset` (see [db.seed] in config.toml).
-- Content is illustrative demo data; replace with production data via Admin.

truncate table printers, parts, settings restart identity cascade;

-- Settings
insert into settings (key, value) values ('contact', '{"whatsapp": "+966 59 338 0390", "phone": "+966 59 338 0390", "email": "Support@fngtradingco.com"}'::jsonb);
insert into settings (key, value) values ('videos', '{"divider1": "/videos/forest-animation.mp4", "divider2": "/videos/botanical-vortex.mp4"}'::jsonb);
insert into settings (key, value) values ('social_media', '{"facebook": "https://facebook.com/fngtradingco", "instagram": "https://instagram.com/fngtradingco", "linkedin": "https://www.linkedin.com/company/fngtradingco", "twitter": ""}'::jsonb);
insert into settings (key, value) values ('seo', '{"title": "Future Next Gen — Refurbished HP Printers & Eco Toner in Saudi Arabia", "description": "FNG supplies professionally refurbished HP printers, eco-friendly toner and genuine printer parts across Saudi Arabia and the Gulf."}'::jsonb);
insert into settings (key, value) values ('ai_settings', '{"welcome_message": "Hi! I''m Nexia, the FNG assistant. Ask me about refurbished HP printers, eco-toner, parts, or getting a quote.", "system_prompt": "You are Nexia, the helpful assistant for FNG (Future Next Gen), a Riyadh-based supplier of refurbished HP printers, eco-friendly toner and printer parts. Be concise, accurate and friendly. If unsure, point the customer to WhatsApp."}'::jsonb);
insert into settings (key, value) values ('admin_password', '"fng-admin-2026"'::jsonb);

-- Printers & equipment
insert into printers (id, name, desc_en, desc_ar, images, features_en, features_ar, specs_en, specs_ar, available) values ('hp-m428fdw', 'HP LaserJet Pro MFP M428fdw', 'Refurbished to factory standard — a fast A4 mono multifunction built for busy offices. Print, copy, scan and fax with automatic two-sided printing and secure Wi-Fi.', 'مُجددة إلى معايير المصنع — طابعة أحادية اللون A4 متعددة الوظائف وسريعة، مصممة للمكاتب المزدحمة. طباعة ونسخ ومسح وفاكس مع طباعة تلقائية على الوجهين وواي فاي آمن.', '{"/printers/HP LaserJet Pro MFP M428fdw/HP LaserJet Pro MFP M428fdw.png","/printers/HP LaserJet Pro MFP M428fdw/HP LaserJet Pro MFP M428fdw2.png","/printers/HP LaserJet Pro MFP M428fdw/HP LaserJet Pro MFP M428fdw3.png","/printers/HP LaserJet Pro MFP M428fdw/HP LaserJet Pro MFP M428fdw4.png","/printers/HP LaserJet Pro MFP M428fdw/HP LaserJet Pro MFP M428fdw5.png","/printers/HP LaserJet Pro MFP M428fdw/HP LaserJet Pro MFP M428fdw7.webp","/printers/HP LaserJet Pro MFP M428fdw/HP LaserJet Pro MFP M428fdw8.webp"}', '{"Up to 40 ppm mono print speed","Automatic duplex print, copy & scan","50-sheet ADF · 250-sheet input tray","Wi-Fi, Ethernet & USB · mobile print","12-month FNG refurbishment warranty"}', '{"سرعة طباعة تصل إلى 40 صفحة/دقيقة","طباعة ونسخ ومسح تلقائي على الوجهين","وحدة تغذية 50 ورقة · درج إدخال 250 ورقة","واي فاي وإيثرنت و USB · طباعة من الجوال","ضمان تجديد FNG لمدة 12 شهراً"}', '{"Functions": "Print, Copy, Scan, Fax", "Print speed": "Up to 40 ppm", "Print quality": "1200 x 1200 dpi", "Paper size": "A4 / Letter", "Connectivity": "Wi-Fi, Ethernet, USB", "Duty cycle": "Up to 80,000 pages/mo"}'::jsonb, '{"الوظائف": "طباعة، نسخ، مسح، فاكس", "سرعة الطباعة": "حتى 40 صفحة/دقيقة", "جودة الطباعة": "1200 × 1200 نقطة/بوصة", "حجم الورق": "A4 / Letter", "الاتصال": "واي فاي، إيثرنت، USB", "دورة التشغيل": "حتى 80,000 صفحة/شهر"}'::jsonb, true);
insert into printers (id, name, desc_en, desc_ar, images, features_en, features_ar, specs_en, specs_ar, available) values ('hp-3303fdw', 'HP Color LaserJet Pro MFP 3303fdw', 'Vivid, dependable colour for documents that need to look their best. A compact colour MFP with fast first-page-out and low running cost on FNG eco-toner.', 'ألوان زاهية وموثوقة للمستندات التي تحتاج أن تظهر بأفضل صورة. طابعة ملوّنة متعددة الوظائف ومدمجة مع إخراج سريع للصفحة الأولى وتكلفة تشغيل منخفضة مع حبر FNG البيئي.', '{"/printers/HP Color LaserJet Pro MFP 3303fdw (499M8A)/HP Color LaserJet Pro MFP 3303fdw (499M8A).png","/printers/HP Color LaserJet Pro MFP 3303fdw (499M8A)/HP Color LaserJet Pro MFP 3303fdw (499M8A)2.png","/printers/HP Color LaserJet Pro MFP 3303fdw (499M8A)/HP Color LaserJet Pro MFP 3303fdw (499M8A)3.png","/printers/HP Color LaserJet Pro MFP 3303fdw (499M8A)/HP Color LaserJet Pro MFP 3303fdw (499M8A)4.png","/printers/HP Color LaserJet Pro MFP 3303fdw (499M8A)/HP Color LaserJet Pro MFP 3303fdw (499M8A)5.png"}', '{"Up to 25 ppm colour & mono","Automatic duplex print, copy & scan","Single-pass 50-sheet ADF","Wi-Fi, Ethernet & USB · mobile print","12-month FNG refurbishment warranty"}', '{"حتى 25 صفحة/دقيقة ملون وأحادي","طباعة ونسخ ومسح تلقائي على الوجهين","وحدة تغذية 50 ورقة بمسار واحد","واي فاي وإيثرنت و USB · طباعة من الجوال","ضمان تجديد FNG لمدة 12 شهراً"}', '{"Functions": "Print, Copy, Scan, Fax", "Print speed": "Up to 25 ppm colour", "Print quality": "600 x 600 dpi", "Paper size": "A4 / Letter", "Connectivity": "Wi-Fi, Ethernet, USB", "Duty cycle": "Up to 40,000 pages/mo"}'::jsonb, '{"الوظائف": "طباعة، نسخ، مسح، فاكس", "سرعة الطباعة": "حتى 25 صفحة/دقيقة ملون", "جودة الطباعة": "600 × 600 نقطة/بوصة", "حجم الورق": "A4 / Letter", "الاتصال": "واي فاي، إيثرنت، USB", "دورة التشغيل": "حتى 40,000 صفحة/شهر"}'::jsonb, true);
insert into printers (id, name, desc_en, desc_ar, images, features_en, features_ar, specs_en, specs_ar, available) values ('hp-m575', 'HP LaserJet Enterprise 500 Color MFP M575', 'Enterprise-grade A4 colour workhorse with full trays, refurbished and load-tested for high-volume departments that can''t afford downtime.', 'طابعة ملوّنة A4 بمستوى المؤسسات مع أدراج كاملة، مُجددة ومُختبرة تحت الحِمل للأقسام عالية الإنتاجية التي لا تحتمل التوقف.', '{"/printers/HP LaserJet Enterprise 500 Color MFP M575 A4 Laser Printer with Full Trays/Untitled.png"}', '{"Up to 30 ppm colour & mono","Full paper-tray configuration included","Large colour touchscreen","Gigabit Ethernet & USB","12-month FNG refurbishment warranty"}', '{"حتى 30 صفحة/دقيقة ملون وأحادي","تكوين أدراج ورق كامل مضمّن","شاشة لمس ملوّنة كبيرة","إيثرنت جيجابت و USB","ضمان تجديد FNG لمدة 12 شهراً"}', '{"Functions": "Print, Copy, Scan, Fax", "Print speed": "Up to 30 ppm colour", "Print quality": "1200 x 1200 dpi", "Paper size": "A4 / Letter", "Connectivity": "Gigabit Ethernet, USB", "Duty cycle": "Up to 120,000 pages/mo"}'::jsonb, '{"الوظائف": "طباعة، نسخ، مسح، فاكس", "سرعة الطباعة": "حتى 30 صفحة/دقيقة ملون", "جودة الطباعة": "1200 × 1200 نقطة/بوصة", "حجم الورق": "A4 / Letter", "الاتصال": "إيثرنت جيجابت، USB", "دورة التشغيل": "حتى 120,000 صفحة/شهر"}'::jsonb, true);
insert into printers (id, name, desc_en, desc_ar, images, features_en, features_ar, specs_en, specs_ar, available) values ('hp-m404dn', 'HP LaserJet Pro M404dn', 'A no-nonsense single-function mono printer for teams that just need fast, reliable pages. Compact footprint, network-ready, refurbished to factory standard.', 'طابعة أحادية اللون بسيطة وذات وظيفة واحدة للفرق التي تحتاج صفحات سريعة وموثوقة. حجم مدمج، جاهزة للشبكة، مُجددة إلى معايير المصنع.', '{}', '{"Up to 40 ppm mono print speed","Automatic two-sided printing","250-sheet input tray","Ethernet & USB · mobile print","12-month FNG refurbishment warranty"}', '{"سرعة طباعة تصل إلى 40 صفحة/دقيقة","طباعة تلقائية على الوجهين","درج إدخال 250 ورقة","إيثرنت و USB · طباعة من الجوال","ضمان تجديد FNG لمدة 12 شهراً"}', '{"Functions": "Print", "Print speed": "Up to 40 ppm", "Print quality": "1200 x 1200 dpi", "Paper size": "A4 / Letter", "Connectivity": "Ethernet, USB", "Duty cycle": "Up to 80,000 pages/mo"}'::jsonb, '{"الوظائف": "طباعة", "سرعة الطباعة": "حتى 40 صفحة/دقيقة", "جودة الطباعة": "1200 × 1200 نقطة/بوصة", "حجم الورق": "A4 / Letter", "الاتصال": "إيثرنت، USB", "دورة التشغيل": "حتى 80,000 صفحة/شهر"}'::jsonb, true);
insert into printers (id, name, desc_en, desc_ar, images, features_en, features_ar, specs_en, specs_ar, available) values ('hp-3301fdw', 'HP Color LaserJet Pro MFP 3301fdw', 'The compact colour MFP for smaller teams — the same trusted engine as the 3303, tuned for lighter monthly volumes at an entry price on FNG eco-toner.', 'الطابعة الملوّنة المدمجة متعددة الوظائف للفرق الأصغر — نفس المحرك الموثوق للطراز 3303، مضبوطة لأحجام شهرية أخف وبسعر مبدئي مع حبر FNG البيئي.', '{"/printers/HP Color LaserJet Pro MFP 3303fdw (499M8A)/HP Color LaserJet Pro MFP 3303fdw (499M8A)2.png","/printers/HP Color LaserJet Pro MFP 3303fdw (499M8A)/HP Color LaserJet Pro MFP 3303fdw (499M8A)4.png","/printers/HP Color LaserJet Pro MFP 3303fdw (499M8A)/HP Color LaserJet Pro MFP 3303fdw (499M8A)5.png"}', '{"Up to 22 ppm colour & mono","Automatic duplex print & scan","50-sheet ADF","Wi-Fi, Ethernet & USB","12-month FNG refurbishment warranty"}', '{"حتى 22 صفحة/دقيقة ملون وأحادي","طباعة ومسح تلقائي على الوجهين","وحدة تغذية 50 ورقة","واي فاي وإيثرنت و USB","ضمان تجديد FNG لمدة 12 شهراً"}', '{"Functions": "Print, Copy, Scan, Fax", "Print speed": "Up to 22 ppm colour", "Print quality": "600 x 600 dpi", "Paper size": "A4 / Letter", "Connectivity": "Wi-Fi, Ethernet, USB", "Duty cycle": "Up to 30,000 pages/mo"}'::jsonb, '{"الوظائف": "طباعة، نسخ، مسح، فاكس", "سرعة الطباعة": "حتى 22 صفحة/دقيقة ملون", "جودة الطباعة": "600 × 600 نقطة/بوصة", "حجم الورق": "A4 / Letter", "الاتصال": "واي فاي، إيثرنت، USB", "دورة التشغيل": "حتى 30,000 صفحة/شهر"}'::jsonb, true);
insert into printers (id, name, desc_en, desc_ar, images, features_en, features_ar, specs_en, specs_ar, available) values ('hp-m428fdn', 'HP LaserJet Pro MFP M428fdn', 'The wired sibling of the M428fdw for fleets standardised on Ethernet. Same fast mono engine, same FNG refurbishment and warranty — currently on request.', 'الشقيق السلكي للطراز M428fdw للأساطيل المعتمدة على إيثرنت. نفس محرك الطباعة الأحادي السريع، نفس تجديد وضمان FNG — متوفر عند الطلب حالياً.', '{}', '{"Up to 40 ppm mono print speed","Automatic duplex print, copy & scan","50-sheet ADF · 250-sheet tray","Ethernet & USB","12-month FNG refurbishment warranty"}', '{"سرعة طباعة تصل إلى 40 صفحة/دقيقة","طباعة ونسخ ومسح تلقائي على الوجهين","وحدة تغذية 50 ورقة · درج 250 ورقة","إيثرنت و USB","ضمان تجديد FNG لمدة 12 شهراً"}', '{"Functions": "Print, Copy, Scan, Fax", "Print speed": "Up to 40 ppm", "Print quality": "1200 x 1200 dpi", "Paper size": "A4 / Letter", "Connectivity": "Ethernet, USB", "Duty cycle": "Up to 80,000 pages/mo"}'::jsonb, '{"الوظائف": "طباعة، نسخ، مسح، فاكس", "سرعة الطباعة": "حتى 40 صفحة/دقيقة", "جودة الطباعة": "1200 × 1200 نقطة/بوصة", "حجم الورق": "A4 / Letter", "الاتصال": "إيثرنت، USB", "دورة التشغيل": "حتى 80,000 صفحة/شهر"}'::jsonb, false);
insert into printers (id, name, desc_en, desc_ar, images, features_en, features_ar, specs_en, specs_ar, available) values ('eq-hermanchair', 'Herman Miller Aeron (Refurbished)', 'Certified pre-owned ergonomic task chair, fully serviced. Office fit-out and bulk pricing available alongside your printer fleet.', 'كرسي مكتب مريح مُعتمد ومُستعمل، تمت صيانته بالكامل. تجهيز مكتبي وأسعار الجملة متوفرة إلى جانب أسطول طابعاتك.', '{"/herman_chair.png"}', '{"Fully serviced & sanitised","Ergonomic lumbar support","Bulk & office fit-out pricing","Delivered and installed"}', '{"تمت صيانته وتعقيمه بالكامل","دعم قطني مريح","أسعار الجملة وتجهيز المكاتب","التوصيل والتركيب"}', '{"Category": "Office seating", "Condition": "Certified refurbished", "Warranty": "6 months"}'::jsonb, '{"الفئة": "أثاث مكتبي", "الحالة": "مُجدد ومُعتمد", "الضمان": "6 أشهر"}'::jsonb, true);

-- Parts
insert into parts (category, name_en, name_ar, models) values ('fuser', 'Fuser Unit (Complete)', 'وحدة التثبيت الحراري (كاملة)', 'M402, M404, M428, M575, 3303fdw');
insert into parts (category, name_en, name_ar, models) values ('fuser', 'Fuser Film Sleeve', 'غلاف فيلم التثبيت', 'M402, M404, M426');
insert into parts (category, name_en, name_ar, models) values ('fuser', 'Pressure Roller', 'أسطوانة الضغط', 'M400 / M500 Series');
insert into parts (category, name_en, name_ar, models) values ('fuser', 'Fuser Gear Kit', 'طقم تروس التثبيت', 'M402, M426, M428');
insert into parts (category, name_en, name_ar, models) values ('pickup', 'Paper Pickup Roller', 'أسطوانة سحب الورق', 'M402, M404, M428, M575');
insert into parts (category, name_en, name_ar, models) values ('pickup', 'Separation Pad', 'وسادة الفصل', 'M402, M404, M426, M428');
insert into parts (category, name_en, name_ar, models) values ('pickup', 'Feed Roller Assembly', 'مجموعة أسطوانة التغذية', 'M575, M551, 3303fdw');
insert into parts (category, name_en, name_ar, models) values ('pickup', 'Tray 2 Roller Kit', 'طقم أسطوانات الدرج ٢', 'M402, M404, M428');
insert into parts (category, name_en, name_ar, models) values ('transfer', 'Transfer Belt (ITB)', 'حزام النقل (ITB)', 'M575, M551, 3303fdw');
insert into parts (category, name_en, name_ar, models) values ('transfer', 'Transfer Roller', 'أسطوانة النقل', 'M402, M404, M426, M428');
insert into parts (category, name_en, name_ar, models) values ('transfer', 'Secondary Transfer Roller', 'أسطوانة النقل الثانوية', 'M575, M551');
insert into parts (category, name_en, name_ar, models) values ('drum', 'OPC Drum', 'أسطوانة OPC', 'All HP LaserJet');
insert into parts (category, name_en, name_ar, models) values ('drum', 'Drum Unit (Complete)', 'وحدة الأسطوانة (كاملة)', 'M402, M404, M428');
insert into parts (category, name_en, name_ar, models) values ('drum', 'Imaging Drum Kit', 'طقم أسطوانة التصوير', 'M575, M551, 3303fdw');
insert into parts (category, name_en, name_ar, models) values ('drum', 'Developer Unit', 'وحدة التظهير', 'M575, M551');
insert into parts (category, name_en, name_ar, models) values ('formatter', 'Formatter Board', 'لوحة المعالج', 'M402, M404, M428, M575');
insert into parts (category, name_en, name_ar, models) values ('formatter', 'Power Supply Board', 'لوحة التغذية الكهربائية', 'M402, M404, M426');
insert into parts (category, name_en, name_ar, models) values ('formatter', 'DC Controller Board', 'لوحة التحكم DC', 'M575, M551');
insert into parts (category, name_en, name_ar, models) values ('formatter', 'Engine Control Board', 'لوحة التحكم بالمحرك', 'M402, M428');
insert into parts (category, name_en, name_ar, models) values ('scanner', 'ADF Roller Kit', 'طقم أسطوانات ADF', 'M428, M575, 3303fdw');
insert into parts (category, name_en, name_ar, models) values ('scanner', 'Scanner Glass Assembly', 'مجموعة زجاج الماسح', 'M428, M575, 3303fdw');
insert into parts (category, name_en, name_ar, models) values ('scanner', 'Flatbed Scanner Cable', 'كابل الماسح المسطح', 'M428, M575');
insert into parts (category, name_en, name_ar, models) values ('scanner', 'ADF Separation Pad', 'وسادة فصل ADF', 'M428, M575, 3303fdw');
insert into parts (category, name_en, name_ar, models) values ('trays', 'Paper Tray Cassette (Tray 2)', 'درج ورق (الدرج ٢)', 'M402, M404, M428');
insert into parts (category, name_en, name_ar, models) values ('trays', 'Multipurpose (MP) Tray', 'الدرج متعدد الأغراض', 'M575, M551');
insert into parts (category, name_en, name_ar, models) values ('trays', 'Output Bin Assembly', 'مجموعة صندوق الإخراج', 'M402, M404, M428');
insert into parts (category, name_en, name_ar, models) values ('trays', 'Front Cover / Access Door', 'الغطاء الأمامي', 'M400 / M500 Series');
insert into parts (category, name_en, name_ar, models) values ('trays', 'Rear Cover Assembly', 'مجموعة الغطاء الخلفي', 'M402, M404');
insert into parts (category, name_en, name_ar, models) values ('maintenance', 'Maintenance Kit (Fuser + Rollers + Pads)', 'طقم صيانة كامل', 'M402, M404');
insert into parts (category, name_en, name_ar, models) values ('maintenance', 'LaserJet MFP Maintenance Kit', 'طقم صيانة LaserJet MFP', 'M428, M575, 3303fdw');
insert into parts (category, name_en, name_ar, models) values ('maintenance', 'ADF Maintenance Kit', 'طقم صيانة ADF', 'M428, M575');
