-- 1. Create Printers Table
CREATE TABLE IF NOT EXISTS printers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    desc_en TEXT,
    desc_ar TEXT,
    images TEXT[] DEFAULT '{}',
    features_en TEXT[] DEFAULT '{}',
    features_ar TEXT[] DEFAULT '{}',
    specs_en JSONB DEFAULT '{}',
    specs_ar JSONB DEFAULT '{}',
    available BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Create Parts Table
CREATE TABLE IF NOT EXISTS parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name_en TEXT NOT NULL,
    name_ar TEXT NOT NULL,
    models TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Create Settings Table
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
-- For now, we allow public read and authenticated write (or just public for this simple setup)
ALTER TABLE printers ENABLE ROW LEVEL SECURITY;
ALTER TABLE parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Create Policies (Allow all for simplicity, or restrict if needed)
CREATE POLICY "Public Read" ON printers FOR SELECT USING (true);
CREATE POLICY "Public Read" ON parts FOR SELECT USING (true);
CREATE POLICY "Public Read" ON settings FOR SELECT USING (true);

-- For admin updates (In a real app, use auth.uid() checks)
CREATE POLICY "Allow All" ON printers FOR ALL USING (true);
CREATE POLICY "Allow All" ON parts FOR ALL USING (true);
CREATE POLICY "Allow All" ON settings FOR ALL USING (true);

-- 4. Create Inquiries Table
CREATE TABLE IF NOT EXISTS inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL, -- 'contact', 'printer_request'
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    phone TEXT NOT NULL,
    city TEXT,
    quantity TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Insert" ON inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow All" ON inquiries FOR ALL USING (true);
