-- 1. Create Printers Table
CREATE TABLE IF NOT EXISTS printers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    desc_en TEXT,
    desc_ar TEXT,
    images TEXT[] DEFAULT '{}',
    features_en TEXT[] DEFAULT '{}',
    features_ar TEXT[] DEFAULT '{}',
    specs_en JSONB DEFAULT '{}',
    specs_ar JSONB DEFAULT '{}',
    available BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Create Parts Table
CREATE TABLE IF NOT EXISTS parts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name_en TEXT NOT NULL,
    name_ar TEXT NOT NULL,
    models TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Create Settings Table
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
--
-- Design: the Next.js app never talks to Supabase directly from the browser.
-- Every read and write goes through server-side API routes using the
-- service-role key (supabaseAdmin in src/lib/supabase.ts), which bypasses
-- RLS entirely. These policies exist only to define what the PUBLIC anon
-- key — embedded in every visitor's browser bundle — is allowed to do if
-- it were ever used directly:
--   - printers / parts: public catalog data, safe to read directly. No
--     insert/update/delete for anon; only service_role can write.
--   - settings / inquiries: no anon policies at all. settings holds the
--     admin password and site config; inquiries holds customer PII. Both
--     are written exclusively via the service-role API routes, so anon
--     gets zero access — not even insert.
ALTER TABLE printers ENABLE ROW LEVEL SECURITY;
ALTER TABLE parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read: printers" ON printers FOR SELECT USING (true);
CREATE POLICY "Public read: parts" ON parts FOR SELECT USING (true);
-- Intentionally no policies on settings: anon/authenticated get no access
-- at all (SELECT, INSERT, UPDATE, DELETE all denied by default under RLS).

-- 4. Create Inquiries Table
CREATE TABLE IF NOT EXISTS inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL, -- 'contact', 'printer_request'
    name TEXT NOT NULL,
    company TEXT NOT NULL,
    phone TEXT NOT NULL,
    city TEXT,
    quantity TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
-- Intentionally no policies here either: lead forms POST to /api/contact
-- and /api/printer-request, which insert via the service-role client.
-- The anon key has no direct access to this table.
